/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Yogi
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dash
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton1.setBackground(new java.awt.Color(0, 255, 204));
        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/deposit.png"))); // NOI18N
        jToggleButton1.setText("Deposit");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 170, 80));

        jToggleButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/withdrawal (1).png"))); // NOI18N
        jToggleButton2.setText("Withdrawl");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 200, 80));

        jLabel1.setBackground(new java.awt.Color(153, 255, 255));
        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 255));
        jLabel1.setText("DASHBOARD");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/exit1.png"))); // NOI18N
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 180, 70));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/money-transfer (1).png"))); // NOI18N
        jButton2.setText("Transfer Money");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, 80));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/loan.png"))); // NOI18N
        jButton3.setText("Apply for Loan");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 200, 70));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/help.png"))); // NOI18N
        jButton4.setText("Help Desk");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 180, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/pexels-hasan-albari-1229861 (1).jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        String num1,num2;
               num1 = JOptionPane.showInputDialog(null, "Please Confirm Your Account Number:-", "Deposit Money", 1);
               int num3 = Integer.parseInt(num1);
               num2 = JOptionPane.showInputDialog(null, "Enter Amount to Deposit:-", "Deposit Money", 1);
               double num4 = Double.parseDouble(num2);
               try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Bank_Management","root","0007");
            Statement stmt = conn.createStatement();
            String query = "select * from Account_Details where AccountNumber="+num3+";";
            System.out.println("Query = " + query);
            ResultSet rs = stmt.executeQuery(query);
            rs.next();
            double balance = rs.getDouble("AccountBalance");
            double newbalance = balance+num4;
            String query2 = "update Account_Details set AccountBalance = '"+newbalance+"'where AccountNumber="+num3+";";
                    stmt.execute(query2);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "Click Yes to Logout");
        dispose();
        new Login().show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        String num1,num2;
               num1 = JOptionPane.showInputDialog(null, "Please Confirm Your Account Number:-", "Withdrawl Money", 1);
               int num3 = Integer.parseInt(num1);
               num2 = JOptionPane.showInputDialog(null, "Enter Amount to Withdraw:-", "Withdrawl Money", 1);
               double num4 = Double.parseDouble(num2);
               try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Bank_Management","root","0007");
            Statement stmt = conn.createStatement();
            String query = "select * from Account_Details where AccountNumber="+num3+";";
            System.out.println("Query = " + query);
            ResultSet rs = stmt.executeQuery(query);
            rs.next();
            double balance = rs.getDouble("AccountBalance");
            double newbalance = balance-num4;
            String query2 = "update Account_Details set AccountBalance = '"+newbalance+"'where AccountNumber="+num3+";";
                    stmt.execute(query2);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String num1,num2,num5;
               num1 = JOptionPane.showInputDialog(null, "Please Confirm Your Account Number:-", "Transfer Money", 1);
               int num3 = Integer.parseInt(num1);
               num5 = JOptionPane.showInputDialog(null, "Enter Beneficiary Account Number:-", "Transfer Money", 1);
               int num6 = Integer.parseInt(num5);
               num2 = JOptionPane.showInputDialog(null, "Enter Amount to Transfer:-", "Transfer Money", 1);
               double num4 = Double.parseDouble(num2);
               try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Bank_Management","root","0007");
            Statement stmt = conn.createStatement();
            Statement stmt1 = conn.createStatement();
            String query = "select * from Account_Details where AccountNumber="+num3+";";
            ResultSet rs = stmt.executeQuery(query);
            rs.next();
            String query0 = "select * from Account_Details where AccountNumber="+num6+";";
            ResultSet rs1 = stmt1.executeQuery(query0);
            rs1.next();
            double balance1 = rs.getDouble("AccountBalance");
            double balance2 = rs1.getDouble("AccountBalance");
            double newbalance1 = balance1-num4;
            double newbalance2 = balance2+num4;
            String query1 = "update Account_Details set AccountBalance = '"+newbalance1+"'where AccountNumber="+num3+";";
            stmt.execute(query1);
            String query2 = "update Account_Details set AccountBalance = '"+newbalance2+"'where AccountNumber="+num6+";";
            stmt.execute(query2);
        } 
               catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Enter Correct Account Number");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
